{
 "title": "Main dashboard",
 "tags": [
  "Linux",
  "Windows",
  "Common metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "group", "query": { "query": "label_values(group)" } },
   {
    "name": "linux_host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$linux_job\"},instance)"
    }
   },
   {
    "name": "win_host",
    "query": {
     "query": "label_values(windows_cs_hostname{job=\"$win_job\"},instance)"
    }
   },
   {
    "name": "linux_job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "win_job",
    "query": {
     "query": "label_values(windows_cs_hostname,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{group=~\"${group}\", instance=~\"${win_host}\"} - windows_os_physical_memory_free_bytes{group=~\"${group}\", instance=~\"${win_host}\"}) / windows_cs_physical_memory_bytes{group=~\"${group}\", instance=~\"${win_host}\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{group=~\"${group}\", instance=~\"${linux_host}\"} - node_memory_MemAvailable_bytes{group=~\"${group}\", instance=~\"${linux_host}\"}) / node_memory_MemTotal_bytes{group=~\"${group}\", instance=~\"${linux_host}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{group=~\"$group\", instance=~\"${win_host}\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{group=~\"$group\", instance=~\"${linux_host}\", mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((windows_logical_disk_size_bytes{group=~\"${group}\", instance=~\"${win_host}\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{group=~\"${group}\", instance=~\"${win_host}\", volume !~\"HarddiskVolume.+\"}) * 100) / windows_logical_disk_size_bytes{group=~\"${group}\", instance=~\"${win_host}\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{instance}}: {{volume}}"
    },
    {
     "expr": "((node_filesystem_size_bytes{group=~\"${group}\", instance=~\"${linux_host}\", device!~'rootfs', mountpoint=~\"(/)\"} - node_filesystem_avail_bytes{group=~\"${group}\", instance=~\"${linux_host}\", device!~'rootfs', mountpoint=~\"(/)\"}) * 100) / node_filesystem_size_bytes{group=~\"${group}\", instance=~\"${linux_host}\", device!~'rootfs', mountpoint=~\"(/)\"}",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{group=~\"${group}\", instance=~\"${linux_host}\"}",
     "legendFormat": "{{instance}}: {{mountpoint}} - Size"
    },
    {
     "expr": "windows_logical_disk_free_bytes{group=~\"${group}\", instance=~\"${win_host}\"}",
     "legendFormat": "{{instance}}: {{volume}}  - Free"
    },
    {
     "expr": "windows_logical_disk_size_bytes{group=~\"${group}\", instance=~\"${win_host}\"}",
     "legendFormat": "{{instance}}: {{volume}}  - Size"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{group=~\"${group}\", instance=~\"${linux_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{group=~\"${group}\", instance=~\"${linux_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{device}} - Writes completed"
    },
    {
     "expr": "irate(windows_logical_disk_reads_total{group=~\"${group}\", instance=~\"${win_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{volume}} - Reads completed"
    },
    {
     "expr": "irate(windows_logical_disk_writes_total{group=~\"${group}\", instance=~\"${win_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{volume}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{group=~\"${group}\", instance=~\"${linux_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{group=~\"${group}\", instance=~\"${linux_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{device}} - Written bytes"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{group=~\"${group}\", instance=~\"${win_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{volume}} - Read bytes"
    },
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{group=~\"${group}\", instance=~\"${win_host}\"}[5m])",
     "legendFormat": "{{instance}}: {{volume}} - Written bytes"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://is.selectel.org\"} - time()",
     "legendFormat": "is.selectel.org"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://chatwoot.selectel.ru/api\"} - time()",
     "legendFormat": "chatwoot.selectel.ru"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://chatwoot.servercore.com/api\"} - time()",
     "legendFormat": "chatwoot.servercore.com"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://boards.selectel.org\"} - time()",
     "legendFormat": "boards.selectel.org"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://bw.selectel.org\"} - time()",
     "legendFormat": "bw.selectel.org"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device!~\"(^enx.*|^f.*|lo|ovs-system|^t.*|^v.*|proxmox|^px.*)\", instance=~\"${linux_host}\", group=~\"${group}\"}[1m])*8)",
     "legendFormat": "{{instance}}-{{device}}_receive"
    },
    {
     "expr": "- (rate(node_network_transmit_bytes_total{device!~\"(^enx.*|^f.*|lo|ovs-system|^t.*|^v.*|proxmox|^px.*)\", instance=~\"${linux_host}\", group=~\"${group}\"}[1m])*8)",
     "legendFormat": "{{instance}}-{{device}}_transmit"
    },
    {
     "expr": "- (rate(windows_net_bytes_sent_total{instance=~\"$win_host\",group=~\"${group}\"}[1m])*8)",
     "legendFormat": "{{instance}}-{{nic}}_transmit"
    },
    {
     "expr": "(rate(windows_net_bytes_sent_total{instance=~\"$win_host\",group=~\"${group}\"}[1m])*8)",
     "legendFormat": "{{instance}}-{{nic}}_transmit"
    }
   ]
  }
 ]
}