- name: create user "is"
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    shell: /bin/bash
    createhome: yes
    groups: sudo

- name: Create folder .ssh
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory

- name: update sudoers configuration
  template:
    src: "templates/sudoers.j2"
    dest: "/etc/sudoers"
    validate: "{{ sudo_visudo }} -cf %s"
    owner: "root"
    group: "root"
    mode: "0440"

- name: change .bashrc
  template:
    src: "templates/.bashrc.j2"
    dest: "/home/{{user_name}}/.bashrc"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: "0644"
